### ISSUE TITLE
Infinite redirect loop: /settings

### ISSUE THREAD

**Issue by D-Ne0** [waartaa/waartaa#122]
When I open '/settings' url directly it gets stuck in an infinite redirect loop.

**Comment by sayanchowdhury** [comment]
Can you tell the steps to reproduce?

**Comment by D-Ne0** [comment]
Just enter this url in address bar: http://localhost:3000/settings

Don't try to go it via settings icon on chat page. It works perfectly fine that way.

**Comment by sayanchowdhury** [comment]
Works fine for me. Can you pull the code i pushed in the afternoon and tell if its working!

**Comment by D-Ne0** [comment]
I pulled the code and checked it on both chrome and firefox.

The problem occurs in Firefox 29.0. I cleared the cache, thought that might be the issue, but that didn't resolve the issue fully. Now it doesn't redirect but no css files are loaded. See the pic below:
![screenshot from 2014-06-15 20 21 52](https://cloud.githubusercontent.com/assets/1271264/3281241/650d2b22-f49d-11e3-9fe2-703144403f9f.png)

Works fine in google chrome though. Seems to me a browser issue either due to meteor or waartaa's code.
